### ISSUE TITLE
报错提问

### ISSUE THREAD

**Issue by xx-iu** [Rooooyy/HiTIN#1]
400000it [00:04, 94226.88it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    train(configs, args)
  File "train.py", line 49, in train
    corpus_vocab = Vocab(config,
  File "E:\CODE\NLP-learning\HiTIN-master\data_modules\vocab.py", line 60, in __init__
    self._count_vocab_from_corpus()
  File "E:\CODE\NLP-learning\HiTIN-master\data_modules\vocab.py", line 106, in _count_vocab_from_corpus
    self._count_vocab_from_sample(data, mode)
  File "E:\CODE\NLP-learning\HiTIN-master\data_modules\vocab.py", line 115, in _count_vocab_from_sample
    for t in line_dict[k]:
KeyError: 'token'

请问为什么wos数据训练一直会有这问题？

**Comment by Rooooyy** [comment]
所有的json数据都要修改一下key, 原始的数据的key都是doc_xxx，需要想办法去掉"doc_"这个前缀，可以运行data/preprocess_json.py来处理，或者直接修改preprocess_wos.py中的key.
