### ISSUE TITLE
为什么处理wos数据集会出现这样的错误？Traceback (most recent call last):   File "F:\paperAndcode\code\HiTIN-master\HiTIN-master\data\preprocess_wos.py", line 178, in <module>     get_hierarchy()   File "F:\paperAndcode\code\HiTIN-master\HiTIN-master\data\preprocess_wos.py", line 160, in get_hierarchy     line = line['doc_label'] KeyError: 'doc_label'

### ISSUE THREAD

**Issue by gunquxuexia** [Rooooyy/HiTIN#2]

**Comment by Rooooyy** [comment]
把'doc_label'手动改为'label'即可。。。

**Comment by gunquxuexia** [comment]
> 把'doc_label'手动改为'label'即可。。。

谢谢您的回答，已成功解决
